version: '3.6'

services:
  zookeeper:
    restart: always
    ports:
      - 2181:2181
    container_name: zookeeper
    build:
      context: .
      dockerfile: zookeeper/Dockerfile
    networks:
      - servernet
    volumes:
      - kafkazoodata:/tmp/zookeeper
  
  server:
    ports:
      - 9092:9092
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://server:9092,PLAINTEXT_INTERNAL://server:29092
      KAFKA_CREATE_TOPICS: 'test'
    networks:
      - servernet    
    volumes:
      - kafkadata:/tmp/kafka-logs
  producer:
    container_name: producer
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - zookeeper
      - server
    networks:
      - servernet

  consumer:
    container_name: consumer
    build:
      context: .
      dockerfile: consumer/Dockerfile
    depends_on:
      - zookeeper
      - server
    networks:
      - servernet
volumes:
  kafkadata:
  kafkazoodata:
networks:
  servernet: 
                
 

